### ISSUE TITLE
Prepare ONE for pandas 3.0

### ISSUE THREAD

**Issue by k1o0** [int-brain-lab/ONE#114]
Ensure no data frames are updated within (i)loc or similar methods:
https://pandas.pydata.org/pandas-docs/version/2.2.0/user_guide/copy_on_write.html#copy-on-write

**Comment by GaelleChapuis** [comment]
Note: Conversion to numpy will create explicit copy

**Comment by oliche** [comment]
So following on the recommendations above, I've setup my pycharm console with the following code.

```
import pandas as pd
pd.options.mode.copy_on_write = "warn"
```

It's a bit disappointing as I didn't receive any warning so far.

**Comment by k1o0** [comment]
Looks like we're in the clear! I think I misread it the first time. We don't appear to assign on views in ONE so it should be fine. I'll close this issue for now.
