### ISSUE TITLE
Is there an issue with ONE.download threads and the Jupyter notebook extension ? 

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/ONE#122]
This has happened twice recently:
Once with a researcher within the IBL, and then again here: https://neurostars.org/t/spikesortingloader-load-spike-sorting-gets-stuck-repeatedly/29560

The download function launches some threads, it may be useful for some staff to install and use VScode to see if this can be reproduced.

**Comment by k1o0** [comment]
This may be resolved by https://github.com/int-brain-lab/ONE/commit/a17cc18b374370e855f1822e68037980473575db. Adding `ONE_HTTP_DL_THREADS=1` will now keep ONE single threaded.  Reopen if necessary...
