### ISSUE TITLE
Can't connect to https://openalyx.internationalbrainlab.org.

### ISSUE THREAD

**Issue by ZhangYH321** [int-brain-lab/ONE#56]
Hello, thank you very much for some open source data. At present, I have encountered some problems in connection，Unable to connect to the public server, showing Service Unavailable

**Comment by juhuntenburg** [comment]
Hi @ZhangYH321 thank you for flagging this issue. We are doing some maintenance on the public server that took a little longer than expected. It should be back up in a few hours from now. 
Thank you for your patience!
